[build]
  publish = "client/dist"
  command = "cd client && npm install && npm run build"
  functions = "netlify/functions"

[dev]
  command = "cd client && npm run dev"
  port = 5173
  targetPort = 5173
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# SPA yönlendirmesi için
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
